### ISSUE TITLE
发现一个项目也许可以替代你重金购买的Extracter啊哈哈

### ISSUE THREAD

**Issue by suckerSlayer** [sh00tg0a1/cpbitmap_convertor#8]
https://github.com/Siguza/imobax
不过没有进行实验，我也是用的你买的这个，不过我用了里面的免费4个文件之后就没再用了，

**Comment by sh00tg0a1** [comment]
为了媳妇的照片，实在是没办法，哈哈哈~

suckerSlayer ***@***.***> 于2022年6月22日周三 13:53写道：
